# -*- coding: utf-8 -*-
"""generer_site_web_entreprises_locales.ipynb

Automatically generated by Colab.

"""

# 📚 Importer les modules
import pandas as pd
import numpy as np
from geopy.geocoders import Nominatim
from geopy.exc import GeocoderTimedOut, GeocoderUnavailable
from time import sleep
from tqdm import tqdm
import folium
from folium.plugins import Fullscreen
import os
from openpyxl import load_workbook

# Charger le fichier excel et lire les feuilles

xls = pd.ExcelFile("site/Informations sur les entreprises.xlsx")

df = pd.read_excel(xls, sheet_name="Entreprises")
df_prod = pd.read_excel(xls, sheet_name="Produits")


# Nettoyage de base
df["Adresse"] = (
    df["Adresse"].astype(str)
                 .str.strip()
                 .str.replace(r"\s+", " ", regex=True)
                 .str.replace("Gatineau(", "Gatineau, ", regex=False)
                 .str.replace(")", "", regex=False)
)

# Compléter ville/province/pays si manquants
def ensure_city(address):
    a = address.strip()
    # Si l’adresse ne contient pas “gatineau” ou “qc”, on append un contexte
    if "gatineau" not in a.lower() and "québec" not in a.lower() and "qc" not in a.lower():
        a = f"{a}, Gatineau, QC, Canada"
    elif "canada" not in a.lower():
        a = f"{a}, Canada"
    return a

df["Adresse_geocode"] = df["Adresse"].apply(ensure_city)

# Enlever les adresses invalides
invalid_tokens = {"", "nan", "none", "pas trouvé", "na"}
df_valides = (
    df[df["Adresse_geocode"].notnull()]
      .copy()
)
df_valides["Adresse_geocode_low"] = df_valides["Adresse_geocode"].str.lower().str.strip()
df_valides = df_valides[~df_valides["Adresse_geocode_low"].isin(invalid_tokens)].copy()

# Initialiser le géocodeur
geolocator = Nominatim(user_agent="carte_pme_gatineau", timeout=10)

# Fonction de géocodage avec pause et gestion d'erreurs
def geocode_adresse(adresse):
    try:
        sleep(1)  # Pause pour éviter le blocage
        location = geolocator.geocode(adresse, exactly_one=True, addressdetails=False)
        if location:
            return location.latitude, location.longitude
    except (GeocoderTimedOut, GeocoderUnavailable):
        return None, None
    except Exception:
        return None, None
    return None, None

# 🧹 Filtrer les adresses valides
df_valides = df[df["Adresse"].notnull() & ~df["Adresse"].str.lower().isin(["nan"])].copy()

# Supprimer les doublons (par exemple sur Nom + Adresse)
nb_avant = len(df_valides)
df_valides = df_valides.drop_duplicates(subset=["Nom de l'entreprise", "Adresse"])
nb_apres = len(df_valides)

if nb_avant > nb_apres:
    print(f"⚠️ {nb_avant - nb_apres} doublon(s) supprimé(s) dans les adresses valides.")

# 📍 Géocoder uniquement si Latitude/Longitude manquantes

# Créer lat/long si absentes aussi dans la copie
for col in ["Latitude", "Longitude"]:
    if col not in df_valides.columns:
        df_valides[col] = pd.Series(dtype="float64")

mask = df_valides["Latitude"].isnull() | df_valides["Longitude"].isnull()

# Liste des adresses à géocoder
adresses = df_valides.loc[mask, "Adresse_geocode"]

# Géocodage avec barre de progression compatible Pandas 2.2+
coords = []
for adresse in tqdm(adresses, desc="Géocodage"):
    lat, lon = geocode_adresse(adresse)
    # Convertir None → np.nan
    if lat is None:
        lat = np.nan
    if lon is None:
        lon = np.nan
    coords.append((lat, lon))

# Convertir en DataFrame pour éviter les erreurs de dtype
coords_df = pd.DataFrame(coords, columns=["Latitude", "Longitude"])

# Injection propre
df_valides.loc[mask, ["Latitude", "Longitude"]] = coords_df.values

# Mettre à jour les coordonnées dans df original
df.update(df_valides[["Latitude", "Longitude"]])

# Ajouter une colonne pour indiquer si le géocodage a réussi
df["geocode_ok"] = df["Latitude"].notnull() & df["Longitude"].notnull()

# Sauvegarde dans le fichier Excel (mise à jour) SANS écraser les autres feuilles

book = load_workbook("site/Informations sur les entreprises.xlsx") # Charger le fichier existant

with pd.ExcelWriter(
    "site/Informations sur les entreprises.xlsx",
    engine="openpyxl",
    mode="a",
    if_sheet_exists="replace"
) as writer:
    # Nouvelle méthode Pandas 2.2 : assigner le classeur via l'attribut _book
    writer._book = book
    writer._sheets = book.worksheets
    df.to_excel(writer, sheet_name="Entreprises", index=False)

# Afficher les entreprises géocodées avec succès
df_valides_final = df[df["geocode_ok"]].copy()
print(df_valides_final[["Nom de l'entreprise", "Adresse","Site internet", "Secteur", "Latitude", "Longitude", "Logo"]])

"""Générer carte"""

# Nettoyer les colonnes pour éviter les NaN
df_valides_final["Site internet"] = df_valides_final["Site internet"].fillna('')
df_valides_final["Secteur"] = df_valides_final["Secteur"].fillna("Secteur non précisé")

# Créer la carte centrée sur Gatineau
carte = folium.Map(location=[45.4765, -75.7013], zoom_start=12)
Fullscreen(position='topright').add_to(carte)

# Dictionnaire secteur → icône  (à modifier pour que cela corresponde aux catégories des entreprises)

secteur_icons = {
    "Agroalimentaire": ("green", "utensils", "fa"),
    "Microbrasserie": ("darkgreen", "beer", "fa"),
    "Arts, spectacles et loisirs": ("purple", "palette", "fa"),
    "Architecture et aménagement": ("darkblue", "drafting-compass", "fa"),
    "Chauffage et Climatisation": ("gray", "thermometer-half", "fa"),
    "Apprentissage, géomètre": ("cadetblue", "ruler-combined", "fa"),
    "Divertissement et pension animale": ("orange", "paw", "fa"),
    "Agence de voyages": ("lightblue", "plane", "fa"),
    "Ameublement, fournitures et accessoires": ("brown", "couch", "fa"),
    "Vente et réparation d'article de plein air": ("olive", "campground", "fa"),
    "Commerce": ("orange", "shopping-cart", "fa"),
    "Services aux entreprises": ("blue", "briefcase", "fa"),
    "Éducation": ("cadetblue", "graduation-cap", "fa"),
    "Santé": ("red", "hospital", "fa"),
    "Construction / Architecture": ("darkblue", "hammer", "fa"),
    "Transport / Logistique": ("lightblue", "truck", "fa"),
    "Finance": ("darkred", "money-bill", "fa"),
    "Technologie / Innovation": ("black", "microchip", "fa"),
    "Nature / Environnement": ("darkgreen", "tree", "fa"),
    "Secteur non précisé": ("gray", "question", "fa")
}

df_valides_final = df_valides_final.dropna(subset=["Latitude", "Longitude"])

# Générer le fichier JSON pour le site
df_valides_final.to_json(
    "site/data/entreprises.json",
    orient="records",
    force_ascii=False,
    indent=2
)


# Boucle sur les entreprises valides
for _, row in df_valides_final.iterrows():
    nom = row["Nom de l'entreprise"]
    secteur = row["Secteur"]
    site = row["Site internet"]
    adresse = row["Adresse"]

    # Bouton cliquable si site valide
    if site and site.startswith("http"):
        bouton_site = f"<a href='{site}' target='_blank' style='display:inline-block; margin-top:6px; padding:6px 12px; background-color:#3498db; color:white; text-decoration:none; border-radius:4px;'>🌐 Visiter le site</a>"
    else:
        bouton_site = "<i>Site web non disponible</i>"

    # Choisir icône selon secteur
    color, icon, prefix = secteur_icons.get(secteur, ("gray", "info-sign", "glyphicon"))

    # HTML stylisé pour le popup
    popup_html = f"""
    <div style='font-family:Arial; font-size:14px; line-height:1.5; max-width:250px;'>
        <h4 style='margin:0; color:#2c3e50;'>{nom}</h4>
        <p style='margin:4px 0;'><strong>Secteur :</strong> {secteur}</p>
        <p style='margin:4px 0;'><strong>Adresse :</strong> {adresse}</p>
        {bouton_site}
    </div>
    """

    popup = folium.Popup(popup_html, max_width=300)

    folium.Marker(
        location=[row["Latitude"], row["Longitude"]],
        popup=popup,
        tooltip=nom,
        icon=folium.Icon(color=color, icon=icon, prefix=prefix)
    ).add_to(carte)

# Sauvegarder la carte dans un fichier HTML
carte.save("site/carte_pme_gatineau.html")

"""Générer la page HTML complète avec navigation + carte

# Style commun des pages
"""

style_css = """
/* style.css */

/* Haut de page */
header {
  background-color: #2a5d84;
  color: white;
  padding: 20px;
  text-align: center;
  display: flex;
  align-items: center;
  justify-content: center;
  gap: 20px;
  flex-wrap: wrap; /* ✅ permet d'adapter sur mobile */
}

header img.logo {
  height: 60px;
  width: auto;
  border-radius: 6px;
}

/* Pour centrer l'en-tête et la barre de navigation visuellement */
header, nav {
  max-width: 1000px;
  margin: 20px auto;
  border-radius: 8px;
  box-shadow: 0 2px 6px rgba(0,0,0,0.1);
}

/* Barre de navigation */
nav {
  background-color: #e0e0e0;
  display: flex;
  justify-content: center;
  gap: 30px;
  padding: 12px 0;
  flex-wrap: wrap; /* ✅ navigation adaptable */
}

nav a {
  text-decoration: none;
  color: #2a5d84;
  font-weight: bold;
  font-size: 16px;
}
nav a:hover {
  text-decoration: underline;
}

body {
  font-family: Arial, sans-serif;
  margin: 0;
  background-color: #f9f9f9;
}

.content {
  max-width: 900px;
  margin: 40px auto;
  padding: 0 20px;
}
h2 {
  color: #2a5d84;
}
p {
  font-size: 18px;
  line-height: 1.6;
  color: #333;
}

/* Pied de page bleu */
footer {
  background-color: #2a5d84;
  color: white;
  text-align: center;
  padding: 20px;
  margin-top: 40px;
}

/* Pour la carte */
iframe {
  width: 100%;
  border: none;
  border-radius: 8px;
  box-shadow: 0 0 10px rgba(0,0,0,0.05);
}

.secteurs {
  margin: 20px;
}

.secteurs section {
  margin-bottom: 40px;
}

/* ✅ Galerie des entreprises */
.entreprises {
  display: flex;
  flex-wrap: wrap;
  gap: 20px;
  justify-content: center; /* centrer sur mobile */
}

.card {
  background: #fff;
  border: 1px solid #ddd;
  border-radius: 8px;
  width: 220px;
  padding: 15px;
  text-align: center;
  box-shadow: 0 2px 6px rgba(0,0,0,0.1);
  transition: transform 0.2s;
}

.card:hover {
  transform: scale(1.05);
}

.card img {
  max-width: 100%;
  height: 120px;
  object-fit: contain;
  margin-bottom: 10px;
}

.card h4 {
  font-size: 1.1em;
  margin: 10px 0;
}

.card a {
  display: inline-block;
  margin-top: 5px;
  color: #007BFF;
  text-decoration: none;
}

.card a:hover {
  text-decoration: underline;
}

.card p {
  font-size: 0.9em;
  color: #555;
  margin: 8px 0;
}


/* ✅ Bloc entreprise avec produits */
.entreprise {
  margin-bottom: 30px;
  padding: 15px;
  border: 1px solid #ddd;
  border-radius: 8px;
  background: #fdfdfd;
}

.entreprise h3 {
  color: #2a5d84;
}

.produits {
  list-style-type: disc;
  margin-left: 20px;
}

.produits li {
  margin: 5px 0;
}

/* ✅ Responsive design */
@media (max-width: 768px) {
  nav {
    flex-direction: column;
    gap: 10px;
  }

  .card {
    width: 100%; /* ✅ cartes prennent toute la largeur sur mobile */
  }

  .content {
    margin: 20px auto;
    padding: 0 10px;
  }

  p {
    font-size: 16px;
  }
}

/* ✅ Bannière d'avertissement */
.banner {
  background-color: #f1c40f;   /* jaune vif */
  color: #2c3e50;              /* texte gris foncé pour contraste */
  text-align: center;          /* centrer le texte */
  font-weight: bold;
  font-size: 16px;
  padding: 12px;
  margin: 10px auto;
  max-width: 1000px;           /* aligné avec header/nav */
  border-radius: 6px;
  box-shadow: 0 2px 6px rgba(0,0,0,0.1);
  display: flex;               /* permet d'ajouter un icône */
  align-items: center;
  justify-content: center;
  gap: 10px;                   /* espace entre icône et texte */
}

.banner .icon {
  font-size: 20px;             /* taille de l'icône */
}

/* Grille des produits */
.produits-grid {
  display: grid;
  grid-template-columns: repeat(auto-fill, minmax(220px, 1fr));
  gap: 16px;
  margin: 12px 0;
}

/* Carte produit */
.product-card {
  background: #fff;
  border: 1px solid #ddd;
  border-radius: 8px;
  overflow: hidden;
  box-shadow: 0 2px 6px rgba(0,0,0,0.08);
  transition: transform 0.2s, box-shadow 0.2s;
}
.product-card:hover {
  transform: translateY(-2px);
  box-shadow: 0 6px 16px rgba(0,0,0,0.12);
}

/* Image */
.product-image {
  background: #f7f7f7;
  display: flex;
  align-items: center;
  justify-content: center;
  height: 160px;
}
.product-image img {
  max-width: 100%;
  max-height: 100%;
  object-fit: contain;
}

/* Infos */
.product-info {
  padding: 12px;
}
.product-name {
  font-weight: 600;
  color: #2a2a2a;
  margin-bottom: 6px;
}
.product-price {
  color: #1a7f37; /* vert style “prix” */
  font-weight: 600;
  margin-bottom: 8px;
}
.product-desc {
  color: #555;
  font-size: 0.92em;
  line-height: 1.4;
}

/* Bouton Voir plus / Voir moins */
.produits-actions {
  margin-top: 8px;
}
.btn-toggle {
  background: #2a5d84;
  color: #fff;
  border: none;
  padding: 8px 14px;
  border-radius: 6px;
  cursor: pointer;
}
.btn-toggle:hover {
  background: #1f4868;
}

/* Bouton Facebook uniquement icône */
.btn-facebook-icon {
  display: inline-block;
  background-color: #1877f2; /* bleu Facebook */
  color: white;
  font-size: 20px; /* taille de l’icône */
  padding: 10px 14px;
  border-radius: 50%; /* cercle autour de l’icône */
  text-align: center;
  transition: background-color 0.2s ease, transform 0.2s ease;
}

.btn-facebook-icon:hover {
  background-color: #145dbf; /* bleu plus foncé au survol */
  transform: scale(1.1); /* petit effet zoom */
}

.btn-facebook-icon i {
  vertical-align: middle;
}
"""
with open("site/style.css", "w", encoding="utf-8") as f:
    f.write(style_css)

"""# En-tête html réutilisable"""

def bloc_entete(titre_page):
    # Dictionnaire des meta descriptions par page
    meta_descriptions = {
        "Accueil": "Bienvenue sur Entreprises locales à Gatineau : découvrez la carte interactive et les commerces locaux à proximité de chez vous.",
        "Liste des entreprises": "Consultez la liste complète des entreprises locales de Gatineau : coordonnées, secteurs d’activité et liens vers leurs sites web.",
        "Produits offerts": "Explorez les produits et services proposés par les entreprises locales de Gatineau, classés par secteur d’activité.",
        "Nous contacter": "Contactez notre équipe pour en savoir davantage sur notre projet et la valorisation des entreprises locales."
    }

    # Choisir la bonne description (par défaut une générique)
    description = meta_descriptions.get(titre_page, "Découvrez les entreprises locales de Gatineau grâce à notre carte interactive et nos listes.")

    return f"""
<!DOCTYPE html>
<html lang="fr">
<head>
  <meta charset="UTF-8">
  <title>{titre_page}</title>

  <!-- SEO -->
  <meta name="description" content="{description}">
  <meta name="keywords" content="Gatineau, entreprises locales, commerce, services, carte interactive, produits locaux">
  <meta name="author" content="Découvrez Gatineau: nos entreprises locales">

  <!-- Accessibilité et affichage -->
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <!-- Open Graph (réseaux sociaux) -->
  <meta property="og:title" content="{titre_page} | Entreprises locales à Gatineau">
  <meta property="og:description" content="{description}">
  <meta property="og:image" content="logo.png">
  <meta property="og:type" content="website">
  <meta property="og:url" content="https://github.com/projet-uqo/entreprises-locales">

  <!-- Favicon -->
  <link rel="icon" href="logo.png" type="image/png">

  <!-- Feuille de style -->
  <link rel="stylesheet" href="style.css">
</head>
<body>
  <header>
    <img src="logo.png" alt="Logo du site" class="logo">
    <h1>Entreprises locales à Gatineau</h1>
  </header>

  <!-- ✅ Bannière d’avertissement -->
  <div class="banner">
    <span class="icon">⚠️</span>
    Ce site est en développement. Au plaisir de vous revoir!
  </div>


  <nav>
    <a href="index.html">Accueil</a>
    <a href="liste.html">Liste des entreprises</a>
    <a href="produits.html">Produits offerts</a>
    <a href="formulaire.html">Ajouter une entreprise</a>
    <a href="contact.html">Nous contacter</a>
  </nav>
  <div class="content">
"""

"""# Pied de page html"""

bloc_footer = """
  </div>
    <footer>
    <p>&copy; 2025 - Découvrez Gatineau: Nos entreprises locales</p>
  </footer>
</body>
</html>
"""

"""# Page d'accueil"""

# Contenu principal
contenu_index = """
<h2>Bienvenue sur notre site</h2>
<p>
  Ce site met en valeur les entreprises locales de la région de Gatineau.
  Vous y trouverez une carte interactive, une liste détaillée des entreprises participantes,
  ainsi que les produits et services qu’elles proposent (si cette information est disponible) .
</p>

<h2>Carte interactive</h2>
<iframe src="carte_pme_gatineau.html" width="100%" height="600" style="border:none; border-radius:8px; box-shadow:0 0 10px rgba(0,0,0,0.05);"></iframe>
"""

# 🧬 Insérer la carte dans le template
html_index = bloc_entete("Accueil – Entreprises locales") + contenu_index + bloc_footer

# 💾 Sauvegarder la page d’accueil avec carte
with open("site/index.html", "w", encoding="utf-8") as f:
    f.write(html_index)

"""# Liste des entreprises"""

# Générer la liste par secteur avec cartes visuelles
liste_html = ""

# Trier les secteurs
secteurs_ordonnes = sorted(df["Secteur"].dropna().unique())

for secteur in secteurs_ordonnes:
    liste_html += f"<section>\n<h2>{secteur}</h2>\n<div class='entreprises'>\n"

    # Filtrer les entreprises du secteur
    entreprises = df[df["Secteur"] == secteur]

    for _, row in entreprises.iterrows():
        nom = row["Nom de l'entreprise"]
        site = row["Site internet"] if pd.notnull(row["Site internet"]) else ""

        # 🔑 Générer directement le chemin web relatif
        if 'Logo' in df.columns and pd.notnull(row['Logo']):
            logo = f"logo/{row['Logo']}"
        else:
            logo = "logo/default.png"

        # Carte visuelle avec description
        description = row["Description"] if "Description" in df.columns and pd.notnull(row["Description"]) else ""

        liste_html += f"""
        <div class="card">
          <img src="{logo}" alt="Logo de {nom}">
          <h4>{nom}</h4>
          <p>{description}</p>
          {"<a href='" + site + "' target='_blank'>Visiter le site</a>" if site else "<i>Site web non disponible</i>"}
        </div>
        """

    liste_html += "</div>\n</section>\n"

html_liste = bloc_entete("Liste des entreprises – Entreprises locales") + liste_html + bloc_footer

# 💾 Sauvegarder la page
with open("site/liste.html", "w", encoding="utf-8") as f:
    f.write(html_liste)

# Produits
# Regrouper les données par secteur et entreprise

# Lire la feuille des produits (deuxième feuille)
df_prod = pd.read_excel("site/Informations sur les entreprises.xlsx", sheet_name="Produits")

df_prod

# 🔧 Nettoyer les colonnes
df.columns = df.columns.str.strip().str.replace("\u00A0", " ").str.replace(r"\s+", " ", regex=True)
df_prod.columns = df_prod.columns.str.strip().str.replace("\u00A0", " ").str.replace(r"\s+", " ", regex=True)

# Initialiser le html
tables_html = ""

# Nombre de produits à afficher en aperçu par entreprise
APERCU_N = 4

# 🔠 Trier les secteurs par ordre alphabétique
secteurs_ordonnes = sorted(df["Secteur"].dropna().unique())

for secteur in secteurs_ordonnes:
    tables_html += f"<section>\n<h2>Secteur : {secteur}</h2>\n"

    # 🏢 Filtrer les entreprises du secteur
    entreprises_du_secteur = df[df["Secteur"] == secteur].groupby("Nom de l'entreprise")

    for entreprise, groupe in entreprises_du_secteur:
        site = str(groupe["Site internet"].iloc[0]).strip() if "Site internet" in df.columns else ""

        tables_html += f"<div class='entreprise'>\n"
        tables_html += f"<h3>{entreprise}</h3>\n"

        # 🔗 Lien vers le site web si disponible
        if pd.notnull(site) and site.strip() != "":
            tables_html += f"<p><a href='{site}' target='_blank'>Visiter le site web</a></p>\n"
        else:
            tables_html += "<p><i>Site web non disponible</i></p>\n"

        # 📦 Liste des produits
        produits_entreprise = df_prod[df_prod["Nom de l'entreprise"] == entreprise]

        if len(produits_entreprise) > 0:
            # Aperçu + reste
            apercu = produits_entreprise.head(APERCU_N)
            reste = produits_entreprise.iloc[APERCU_N:]

            # Grille des cartes
            tables_html += "<div class='produits-grid'>\n"

            # Fonction utilitaire locale pour générer une carte
            def carte_produit_html(prow):
              # Nettoyer les champs
              def safe_str(value):
                if pd.isna(value):
                  return ""
                v = str(value).strip()
                return "" if v.lower() in ["nan", "none", ""] else v

              produit = safe_str(prow.get("Produit", ""))
              prix = safe_str(prow.get("Prix", ""))
              description = safe_str(prow.get("Description", ""))
              image = safe_str(prow.get("Image", ""))

              # Dossier des images: 'produit/'
              img_src = f"produit/{image}" if image else "produit/default.png"

              # Carte HTML
              html = f"""
                <div class="product-card">
                 <div class="product-image"><img src="{img_src}" alt="{produit}"></div>
                 <div class="product-info">
                <div class="product-name">{produit}</div>
              """

              # Prix avec fallback
              if prix:
                html += f"<div class='product-price'>{prix}</div>"
              else:
                html += "<div class='product-price'><i>Aucun prix disponible</i></div>"

              # Description avec fallback
              if description:
                html += f"<div class='product-desc'>{description}</div>"
              else:
                html += "<div class='product-desc'><i>Aucune description disponible</i></div>"

              html += """
                </div>
              </div>
              """
              return html

            # Aperçu visible
            for _, prow in apercu.iterrows():
                tables_html += carte_produit_html(prow)

            tables_html += "</div>\n"  # fin .produits-grid


            # Bloc caché pour le reste
            if len(reste) > 0:
                bloc_id = f"products-{hash(entreprise) % (10**8)}"
                tables_html += f"<div id='{bloc_id}' class='produits-grid produits-cache' style='display:none;'>\n"
                for _, prow in reste.iterrows():
                    tables_html += carte_produit_html(prow)
                tables_html += "</div>\n"

                # Bouton Voir plus / Voir moins
                tables_html += f"""
                <div class="produits-actions">
                  <button class="btn-toggle" data-target="{bloc_id}">Voir plus</button>
                </div>
                """
        else:
            tables_html += "<p><i>Aucun produit ou service n'est repertorié actuellement</i></p>\n"

        tables_html += "</div>\n"

    tables_html += "</section>\n"


# Intégrer dans le modèle
html_produits = bloc_entete("Produits offerts – Entreprises locales") + """
<h2>Produits et services proposés</h2>
<p>Voici les produits classés par secteur et entreprise.</p>
""" + tables_html + """
<script>
  // Toggle "Voir plus" / "Voir moins"
  document.addEventListener('click', function(e) {
    if (e.target && e.target.classList.contains('btn-toggle')) {
      const targetId = e.target.getAttribute('data-target');
      const bloc = document.getElementById(targetId);
      if (!bloc) return;
      const visible = bloc.style.display !== 'none';
      bloc.style.display = visible ? 'none' : 'grid';
      e.target.textContent = visible ? 'Voir plus' : 'Voir moins';
    }
  });
</script>
""" + bloc_footer

# 💾 Sauvegarder
with open("site/produits.html", "w", encoding="utf-8") as f:
    f.write(html_produits)

# -----------------------------------------
# Page ajout d'entreprise
# -----------------------------------------

formulaire_html = f"""
{bloc_entete("Ajouter une entreprise")}

<h2>Proposer une entreprise locale</h2>
<p>Remplissez ce formulaire pour soumettre les informations de l’entreprise pour approbation.</p>

<form id="entrepriseForm">
    <label>Nom de l'entreprise *</label>
    <input type="text" id="nom" required>

    <label>Adresse *</label>
    <input type="text" id="adresse" required>

    <label>Secteur *</label>
    <input type="text" id="secteur" required>

    <label>Site internet</label>
    <input type="url" id="site">

    <label>Logo (URL)</label>
    <input type="url" id="logo">

    <label>Description</label>
    <textarea id="description" rows="4"></textarea>

    <button type="submit">Télécharger la soumission</button>
</form>

<div id="message"></div>

<script>
document.getElementById("entrepriseForm").addEventListener("submit", function(e) {{
    e.preventDefault();

    const data = {{
        nom: document.getElementById("nom").value.trim(),
        adresse: document.getElementById("adresse").value.trim(),
        secteur: document.getElementById("secteur").value.trim(),
        site: document.getElementById("site").value.trim(),
        logo: document.getElementById("logo").value.trim(),
        description: document.getElementById("description").value.trim()
    }};

    if (!data.nom || !data.adresse || !data.secteur) {{
        alert("Veuillez remplir tous les champs obligatoires.");
        return;
    }}

    const blob = new Blob([JSON.stringify(data, null, 4)], {{ type: "application/json" }});
    const filename = "soumission-" + Date.now() + ".json";

    const link = document.createElement("a");
    link.href = URL.createObjectURL(blob);
    link.download = filename;
    link.click();

    document.getElementById("message").innerHTML =
        `<div class="success">Votre fichier a été généré. Envoyez-le à l’administratrice du site pour approbation.</div>`;
}});
</script>

{bloc_footer}
"""

# 💾 Sauvegarder la page formulaire
with open("site/formulaire.html", "w", encoding="utf-8") as f:
    f.write(formulaire_html)

"""# Page de contacts"""

html_contact = bloc_entete("Nous contacter – Entreprises locales") + """
<h2>Contactez notre équipe</h2>
<p>Ce projet est réalisé par l’équipe <strong>Découvez Gatineau: Nos entreprises locales</strong>, dans le cadre d’un travail universitaire visant à valoriser les entreprises locales.</p>

<p class="email">
📧 Pour nous joindre :
<a href="mailto:gaua83@uqo.ca">gaua83@uqo.ca</a>
</p>

<p class="facebook">
   🌐 Retrouvez-nous sur Facebook :
   <a href="https://www.facebook.com/people/Nos-Entreprises-Locales/61584067825922"
      target="_blank"
      class="btn-facebook">
      <i class="fab fa-facebook-f"></i> Nos Entreprises Locales
   </a>
</p>

""" + bloc_footer

# 💾 Sauvegarder la page contact
with open("site/contact.html", "w", encoding="utf-8") as f:
    f.write(html_contact)
